version: '2'
services:
  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: vizfun_node
    labels:
      - "description=node.js"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: vizfun_nginx
    ports:
      - "80:8080"
    links:
      - "node"
    labels:
      - "description=nginx"
