version: '2'
services:

  redis:
    image: redis:4.0.8-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: vizfun_redis
    ports:
      - "6379:6379"
    labels:
      - "description=redis"
    env_file:
      - .env

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: vizfun_node
    links:
      - redis
    labels:
      - "description=node.js"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: vizfun_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - node
    labels:
      - "description=nginx"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
